version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile.Local
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - PYTHONUNBUFFERED=1
      - DATABASE_URL_DEV=postgresql+psycopg2://postgres:postgres@db/grimorios
      - DATABASE_URL_PROD=postgresql+psycopg2://postgres:postgres@db/grimorios
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres 
    ports:
      - "5488:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/utils/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
