version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Local
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
  