FROM python:3.11
ENV PYTHONUNBUFFERED=1

COPY src/requirements.txt ./
RUN pip install -r requirements.txt

COPY . /app
WORKDIR /app

CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
