version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Local
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - PYTHONUNBUFFERED=1
    
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=  
    ports:
      - "5488:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./utils/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
